### ISSUE TITLE
Minutes of meetings 

### ISSUE THREAD

**Issue by groenborg** [Praqma/dilly-dally#1]
Idea generation and brainstorming for the dillydally time logging tool for GitHub issues. It is the startup of the project which originated from the issues related to mapping fogbugz to issues. 
The idea is to log time in comments on GitHub issues through the command line, eventually this could evolve to a service or a bot in slack.

**Comment by lakruzz** [comment]
:did: 2017-06-07T11:00:00+02:00 2017-06-07T13:00:00+02:00 
Attended the brain storm meeting with @groenborg and @buep

**Comment by lakruzz** [comment]
Jeg

**Comment by buep** [comment]
![dsc_1093](https://user-images.githubusercontent.com/1579826/26968750-700aab96-4d03-11e7-8c69-ac531b8ea67a.JPG)

**Comment by buep** [comment]
:did: 2017-06-07T11:00:00+02:00 2017-06-07T13:30:00+02:00

**Comment by buep** [comment]
# My minutes of meeting notes

* Won't allow for notation `/did 2 hours on noops#168` as this could lead to double logging, since not time associated. Insted it will be `/did 1000-1200 noops#168`
